name: 'tangerineFront 이슈 생성'
description: 'tangerineFront Repo에 이슈를 생성하며, 생성된 이슈는 Jira와 연동됩니다.'
labels: [order]
title: '이슈 이름을 작성해주세요'
body:
  - type: input
    id: parentKey
    attributes:
      label: '상위 작업 Ticket Number'
      description: '상위 작업의 Ticket Number를 기입해주세요'
      placeholder: 'TG-00'
    validations:
      required: true

  - type: input
    id: description
    attributes:
      label: '이슈 내용(Description)'
      description: '이슈에 대해서 간략히 설명해주세요'
    validations:
      required: true

  - type: markdown
    id: details
    attributes:
      label: '상세 내용(Details)'
      description: '## 이슈에 대해서 자세히 설명해주세요'
      value: |
        - About Details
    validations:
      required: true
