name: EC2에 배포
on:
  pull_request:
    types: [closed]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: EC2에 배포
      env:
        PRIVATE_KEY: ${{ secrets.EC2_PRIVATE_KEY }}
        HOST: ${{ secrets.EC2_HOST }}
        USER: ${{ secrets.EC2_USER }}
      run: |
        echo "$PRIVATE_KEY" > private_key && chmod 600 private_key
        scp -i private_key -o StrictHostKeyChecking=no docker-compose-prod.yml ${USER}@${HOST}:~/
        scp -i private_key -o StrictHostKeyChecking=no pyproject.toml ${USER}@${HOST}:~/
        ssh -i private_key -o StrictHostKeyChecking=no ${USER}@${HOST} '
          cp docker-compose-prod.yml docker-compose.yml
          docker-compose pull
          docker-compose up -d
        '
