name: EC2에 배포
on:
  pull_request:
    types: [closed]
  push:
    branches: [main]
  workflow_dispatch:
jobs:
  deploy:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true || github.event_name == 'push'
    
    steps:
    - uses: actions/checkout@v2
    
    - name: EC2에 배포
      env:
        PRIVATE_KEY: ${{ secrets.EC2_PRIVATE_KEY }}
        HOST: ${{ secrets.EC2_HOST }}
        USER: ${{ secrets.EC2_USER }}
      run: |
        echo "$PRIVATE_KEY" > private_key && chmod 600 private_key
        scp -i private_key -o StrictHostKeyChecking=no docker-compose.yml ${USER}@${HOST}:~/
        ssh -i private_key -o StrictHostKeyChecking=no ${USER}@${HOST} '
          set -e
          
          # 패키지 목록 업데이트
          sudo yum update -y
          
          # libcrypt 설치
          sudo yum install -y libxcrypt-compat
          
          # Docker 설치 (이미 완료됨)
          
          # Docker Compose 설치 (pip를 사용하여 설치)
          sudo yum install -y python3-pip
          sudo pip3 install docker-compose
          
          # Docker와 Docker Compose 버전 확인
          docker --version
          docker-compose --version
          
          # 컨테이너 가져오기 및 시작
          docker-compose pull
          docker-compose up -d
        '
