name: Lint Python Code with Ruff
on:
  pull_request:
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - run: pip install ruff

    - name: Run Ruff
      run: |
        ruff check .
