name: Lint Python Code with Ruff
on:
  push:
  pull_request:
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: Cache Python dependencies
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: Cache Ruff
      uses: actions/cache@v3
      with:
        path: ~/.cache/ruff
        key: ${{ runner.os }}-ruff-${{ hashFiles('**/*.py') }}
        restore-keys: |
          ${{ runner.os }}-ruff-

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install ruff

    - name: Run Ruff
      run: |
        ruff check .
